/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scm_ScmNative */

#ifndef _Included_com_scm_ScmNative
#define _Included_com_scm_ScmNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scm_ScmNative
 * Method:    receiveFdFromBootstrap
 * Signature: (Ljava/lang/String;)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_scm_ScmNative_receiveFdFromBootstrap
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
